/**
 * حالات تجريبية (Demo) تُضاف عند أول تشغيل حتى يفهم المستخدم التطبيق.
 * معلّمة بـ isDemo: true وتظهر بشارة "تجريبية" في الواجهة.
 */
import { DebugCase } from '../domain/types';

const now = Date.now();
const iso = (offsetMin: number) => new Date(now - offsetMin * 60_000).toISOString();

export function buildDemoCases(): DebugCase[] {
  return [
    {
      id: 'demo-1',
      title: 'فشل تسجيل الدخول — HTTP 401',
      description:
        'بعد آخر تحديث للتطبيق، كل محاولات تسجيل الدخول ترجع HTTP 401 رغم صحة كلمة المرور. المشكلة في بيئة الإنتاج وتؤثر على كل المستخدمين.',
      language: 'TypeScript',
      framework: 'React Native',
      platform: 'Android',
      errorMessage: 'Request failed with status code 401 — Unauthorized',
      stackTrace:
        'AxiosError: Request failed with status code 401\n    at settle (axios/lib/core/settle.js:17:12)\n    at XMLHttpRequest.handleLoad (axios/lib/adapters/xhr.js:76:23)\n    at AuthApi.login (src/api/auth.ts:42:18)',
      environment: 'إنتاج — Android 14 — نسخة التطبيق 2.3.1',
      recentChange: 'تحديث مكتبة axios من 1.4 إلى 1.6 وتغيير مكان تخزين التوكن',
      triedFixes: 'إعادة تثبيت التطبيق ومسح الكاش — دون فائدة',
      state: 'verified',
      severity: 'high',
      isDemo: true,
      createdAt: iso(60 * 26),
      updatedAt: iso(60 * 2),
      tags: ['auth', 'production'],
      evidence: [
        {
          id: 'demo-1-ev1',
          caseId: 'demo-1',
          type: 'error',
          title: 'رسالة الخطأ من العميل',
          content: 'HTTP 401 Unauthorized عند POST /api/auth/login',
          createdAt: iso(60 * 25),
          redactionCount: 0,
        },
        {
          id: 'demo-1-ev2',
          caseId: 'demo-1',
          type: 'recent_change',
          title: 'تغيير أخير: تخزين التوكن',
          content: 'نقل التوكن من AsyncStorage إلى SecureStore لكن بدون ترحيل القيم القديمة',
          createdAt: iso(60 * 24),
          redactionCount: 0,
        },
        {
          id: 'demo-1-ev3',
          caseId: 'demo-1',
          type: 'log',
          title: 'سجل بعد الإصلاح',
          content: 'POST /api/auth/login → HTTP 200 OK — user authenticated successfully',
          createdAt: iso(60 * 2),
          redactionCount: 0,
        },
      ],
      diagnosis: {
        hypotheses: [
          {
            ruleId: 'http_401_auth',
            titleAr: 'مشكلة مصادقة (Authentication) محتملة',
            titleEn: 'Possible authentication problem',
            confidence: 0.87,
            supportingEvidenceIds: ['demo-1-ev1', 'demo-1-ev2'],
            suggestedChecksAr: [
              'تحقق من صلاحية التوكن وانتهاء صلاحيته',
              'تأكد من إرسال ترويسة Authorization بالتنسيق الصحيح',
            ],
            suggestedChecksEn: ['Check token validity', 'Verify Authorization header'],
            source: 'local',
          },
        ],
        rootCauseAr: 'مشكلة مصادقة (Authentication) محتملة',
        rootCauseEn: 'Possible authentication problem',
        confidence: 0.87,
        severity: 'high',
        analyzedAt: iso(60 * 20),
        engine: 'local',
        fingerprint: {
          hash: 'demo1fp',
          errorKind: 'http:401',
          signal: 'HTTP 401',
          topFrame: 'auth.ts::login',
          tokens: ['login', 'unauthorized', 'axios'],
        },
      },
      fixPlan: {
        problemAr: 'فشل تسجيل الدخول — HTTP 401',
        problemEn: 'Login fails — HTTP 401',
        causeAr: 'التوكن القديم ضائع بعد تغيير مكان التخزين، فيُرسل طلب بدون هوية صالحة',
        causeEn: 'Old token lost after storage migration; requests sent without valid identity',
        changeAr: 'إضافة منطق ترحيل: قراءة التوكن من التخزين القديم مرة واحدة ونقله للتخزين الآمن',
        changeEn: 'Add migration: read token from old storage once and move it to secure storage',
        whyAr: 'المستخدمون الحاليون فقدوا توكناتهم بعد التحديث فترفضهم الخوادم',
        whyEn: 'Existing users lost tokens after update so servers reject them',
        risk: 'medium',
        impactsAr: ['تدفق تسجيل الدخول', 'الجلسات الحالية'],
        impactsEn: ['Login flow', 'Existing sessions'],
        stepsAr: ['اكتب دالة ترحيل', 'شغلها مرة عند الإقلاع', 'أضف اختبارًا للحالة'],
        stepsEn: ['Write migration', 'Run once at startup', 'Add test'],
        verificationHintAr: 'دليل جديد يظهر HTTP 200 لنفس الطلب',
        verificationHintEn: 'New evidence showing HTTP 200',
        createdAt: iso(60 * 19),
        status: 'applied',
      },
      verifications: [
        {
          id: 'demo-1-v1',
          before: 'HTTP 401',
          after: 'HTTP 200',
          evidenceIds: ['demo-1-ev3'],
          result: 'verified',
          note: 'تم التحقق: نفس الطلب أرجع 200 بعد الترحيل',
          createdAt: iso(60 * 2),
        },
      ],
      fingerprint: {
        hash: 'demo1fp',
        errorKind: 'http:401',
        signal: 'HTTP 401',
        topFrame: 'auth.ts::login',
        tokens: ['login', 'unauthorized', 'axios'],
      },
    },
    {
      id: 'demo-2',
      title: 'تحطم عند فتح صفحة الملف الشخصي — Null Pointer',
      description:
        'التطبيق يتعطل فور فتح صفحة الملف الشخصي للمستخدمين الذين لا يملكون صورة. التعطل في بيئة الإنتاج.',
      language: 'Dart',
      framework: 'Flutter',
      platform: 'iOS',
      errorMessage: 'Null check operator used on a null value',
      stackTrace:
        '#0      ProfileAvatar.build (package:app/widgets/profile_avatar.dart:31:42)\n#1      ProfileScreen.build (package:app/screens/profile_screen.dart:58:12)',
      environment: 'إنتاج — iOS 17 — Flutter 3.24',
      state: 'fix_plan',
      severity: 'critical',
      isDemo: true,
      createdAt: iso(60 * 5),
      updatedAt: iso(60 * 3),
      tags: ['crash', 'flutter'],
      evidence: [
        {
          id: 'demo-2-ev1',
          caseId: 'demo-2',
          type: 'stacktrace',
          title: 'Stack Trace من Crashlytics',
          content:
            'Null check operator used on a null value\n#0 ProfileAvatar.build (profile_avatar.dart:31)',
          createdAt: iso(60 * 5),
          redactionCount: 0,
        },
      ],
      diagnosis: {
        hypotheses: [
          {
            ruleId: 'null_reference',
            titleAr: 'وصول إلى قيمة فارغة (Null/Undefined)',
            titleEn: 'Null/undefined reference',
            confidence: 0.81,
            supportingEvidenceIds: ['demo-2-ev1'],
            suggestedChecksAr: [
              'حدد السطر من Stack Trace وافحص مصدر القيمة',
              'أضف تحققًا اختياريًا أو قيمة افتراضية',
            ],
            suggestedChecksEn: ['Locate line from stack trace', 'Add optional chaining or default'],
            source: 'local',
          },
        ],
        rootCauseAr: 'وصول إلى قيمة فارغة (Null/Undefined)',
        rootCauseEn: 'Null/undefined reference',
        confidence: 0.81,
        severity: 'critical',
        analyzedAt: iso(60 * 4),
        engine: 'local',
        fingerprint: {
          hash: 'demo2fp',
          errorKind: 'null_reference',
          signal: 'Null Reference',
          topFrame: 'profile_avatar.dart::build',
          tokens: ['null', 'profile', 'avatar'],
        },
      },
      fixPlan: {
        problemAr: 'تحطم عند فتح صفحة الملف الشخصي',
        problemEn: 'Crash on profile screen',
        causeAr: 'استخدام معامل ! على صورة قد تكون null للمستخدمين بدون صورة',
        causeEn: 'Using ! operator on possibly-null avatar image',
        changeAr: 'استبدال image! بصورة افتراضية عند null مع widget بديل',
        changeEn: 'Replace image! with a default/fallback widget when null',
        whyAr: 'معامل ! يفترض وجود القيمة بينما هي null في حالة حقيقية',
        whyEn: 'The ! operator assumes non-null while it is null in a real case',
        risk: 'low',
        impactsAr: ['شاشة الملف الشخصي فقط'],
        impactsEn: ['Profile screen only'],
        stepsAr: ['أزل معامل !', 'أضف صورة افتراضية', 'اختبر مستخدمًا بلا صورة'],
        stepsEn: ['Remove ! operator', 'Add fallback', 'Test user without image'],
        verificationHintAr: 'دليل جديد (اختبار أو سجل) يثبت فتح الصفحة بلا تعطل',
        verificationHintEn: 'New evidence the screen opens without crash',
        createdAt: iso(60 * 3),
        status: 'proposed',
      },
      verifications: [],
      fingerprint: {
        hash: 'demo2fp',
        errorKind: 'null_reference',
        signal: 'Null Reference',
        topFrame: 'profile_avatar.dart::build',
        tokens: ['null', 'profile', 'avatar'],
      },
    },
    {
      id: 'demo-3',
      title: 'فشل npm install — تعارض إصدارات',
      description: 'بعد سحب آخر تحديث، npm install يفشل برسالة ERESOLVE.',
      language: 'JavaScript',
      framework: 'Node.js',
      platform: 'macOS',
      errorMessage:
        'npm ERR! ERESOLVE could not resolve — Found: react@18.2.0, peer react@^17.0.0 required',
      environment: 'تطوير — macOS 14 — Node 20',
      state: 'open',
      severity: 'medium',
      isDemo: true,
      createdAt: iso(60 * 1),
      updatedAt: iso(60 * 1),
      tags: ['dependencies'],
      evidence: [],
      diagnosis: undefined,
      fixPlan: undefined,
      verifications: [],
      fingerprint: {
        hash: 'demo3fp',
        errorKind: 'dependency_conflict',
        signal: 'Dependency Conflict',
        tokens: ['eresolve', 'react', 'peer'],
      },
    },
  ];
}
